{
 "title": "OpenVAS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": {
     "query": "label_values(openvas_total_low, server_ip)"
    }
   },
   {
    "name": "ip",
    "query": {
     "query": "label_values(openvas_host_low{server_ip=~\"$server\"}, ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total info for server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total security index for all hosts on server",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 1, "y": 1 },
   "repeat": "server",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openvas_total_sec_index{server_ip=~\"$server\"}",
     "legendFormat": "Total security index | {{server_ip}}"
    }
   ]
  },
  {
   "title": "Total low-level vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "repeat": "server",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openvas_total_low{server_ip=~\"$server\"}",
     "legendFormat": "Low | {{server_ip}}"
    }
   ]
  },
  {
   "title": "Total medium-level vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "repeat": "server",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openvas_total_medium{server_ip=~\"$server\"}",
     "legendFormat": "Medium | {{server_ip}}"
    }
   ]
  },
  {
   "title": "Total high-level vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "repeat": "server",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openvas_total_high{server_ip=~\"$server\"}",
     "legendFormat": "High | {{server_ip}}"
    }
   ]
  },
  {
   "title": "Total security index for all hosts on server",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 1, "y": 8 },
   "targets": [
    {
     "expr": "openvas_total_sec_index{server_ip=~\"$server\"}",
     "legendFormat": "Total security index | {{server_ip}}"
    }
   ]
  },
  {
   "title": "Total low-level vulnerabilities",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "openvas_total_low{server_ip=~\"$server\"}",
     "legendFormat": "Low | {{server_ip}}"
    }
   ]
  },
  {
   "title": "Total medium-level vulnerabilities",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "openvas_total_medium{server_ip=~\"$server\"}",
     "legendFormat": "Medium | {{server_ip}}"
    }
   ]
  },
  {
   "title": "Total high-level vulnerabilities",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "openvas_total_high{server_ip=~\"$server\"}",
     "legendFormat": "High | {{server_ip}}"
    }
   ]
  },
  { "title": "Host info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Host vulnerabilities info",
   "type": "table",
   "gridPos": { "h": 25, "w": 21, "x": 1, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "openvas_host_low{server_ip=~\"$server\", ip=~\"$ip\"}"
    },
    {
     "expr": "openvas_host_medium{server_ip=~\"$server\", ip=~\"$ip\"}"
    },
    {
     "expr": "openvas_host_high{server_ip=~\"$server\", ip=~\"$ip\"}"
    },
    {
     "expr": "openvas_host_sec_index{server_ip=~\"$server\", ip=~\"$ip\"}"
    }
   ]
  }
 ]
}